version: '3'
services:
  postgres:
      image: postgres
      environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      ports:
        - "5432:5432"
  django:
    image: django-dock:0.0.1
    build: .
    command: python jango-assessment/manage.py runserver 0.0.0.0:8000
    ports: 
    - "8000:8000"

    volumes:
    - .:/app
    depends_on:
      - postgres