# Generated by Django 4.1.1 on 2022-10-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("okay", "0004_alter_score_result"),
    ]

    operations = [
        migrations.AlterModelOptions(name="score", options={"managed": False},),
    ]
