# Generated by Django 4.1.1 on 2022-10-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("okay", "0005_alter_score_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="score", options={},),
    ]
