# Generated by Django 4.1.2 on 2022-10-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okay', '0006_alter_score_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
