# Generated by Django 4.1.2 on 2022-10-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okay', '0011_remove_score_result_2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scoring',
        ),
    ]
